sudo: false
dist: trusty
language: node_js
node_js:
- lts/*
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: IP1mMerCu9K5iXaBYhT3wJ9tGWkMuvX3E3Bh6iIMb/JWyjRzkSDdUL2lWZobesXLKBa7Vc29BI2FynfwD0/1HO7IDuFifXLIjjj+91U1hwOsc1b/9YR8/e3zjDCTyPF9LPtUyc5p1JAwvcX6JSgP8qHWij8YGax+UnGJCromtAA/zLJlvJW54lT16WEtTWdupYDK+ESVLwn1/mRsGaUHU5vtKFmbSekKWVnSi+nurdFQyjCup4XuxdZ68fZchpuYYxTka3SnhuVDuBz9cBQaSWnE9MnppFpuTknz4bLsvMdGAqiAr9n1+HVzQR9/PgAeGQn3/lN96SjXG22Uj8Sqp4RagQG7JTYcajVaPmxHOGHQ51wmc0QwJC3UpAYtdcaSHPRCts7KP1u5rW1znC6AcABKJ6uDVcRRGZGBq8r/gwd0FYRtQaixFEzQkFBwnXnkUU/tk9F0FETSytmcWk2007SNKdMmj4MYIh7a3O/PxNmlKzOWV9C06XrM8XfPGetItCIqx8Ignkp+gwhqlbVtm8yCb+8JeXjb6phTgIya+9XmJWqiJnNBqUcEwHlQ2dJrLrkerv7fVKiBaK2yNSaEHoRiG9aaji9E4cUdi8FfGsP/3/I4GJh3gFxcbYftwrjW15YSRt7k4tcSprqSaTzEIudnyjDcirbK9uIW/LPIY/U=
  - secure: Rv3GDcrPF9KW6DAHKqmRWpTB5JxtEgIKtx1FJBGRNbkNQkiPVAUhoDexnhJXXkzGdKoJzgRTym6oQLvuhi4YrtdXf2n0TK1f4jAPZHkyY60R2MFR75jWlSd4eC3iwXWVw2e6XvzWy5N/ZNM8IGUvmLxDzRfsriRDwpskEtC4VDXsfk77L2FAkidNNMtQC9T+txhJ0VRm40kaAUq0z/DeUm0O6kx2sGUUk4wVhjjYSOEtXftKKWMv4E8a9IQDkw/7S8sEW+CljX0uIli7hXqs6kdIRFWmGxYo7aS/17ri4tHQuQKm223HHzDcAaSeDIbONfkyBLbPtkhNUOBfZhSUs375IbNiIEDQjKNzvV6c8s1H5uhTDmKQpSjkNRq4M2FbyVzRR3Q2MKsVWsZBGZcNi9o4ewYxkNyVsYb4AWS/VsH+I5HveeGR9F+ncxqsIUUzH2aUt9eBf+3df8EaHtCRyd8KKvHZjG++5z369B8UIqUU1y1xAXppcBsyGiwDFHaHEeN4JypPYxlNfqn0AMWI2bt8zFHEWVffGrMpuyKp3h4RVb4hLoZ943e6GPgxtb5AVdXkXLGTk2pB4Hssu9nGhVxoiPhTFye/OZ9NrlMql3SEFD6bRCasGkrHYSS1nCK0CJjryxTiaw/OTGFEZw/My5ZRV/fQkLsw2qfzAPLjTY8=
  - secure: XSKF86KODktPGodroBtsHONlid7r6qRIPc7/U1bnDrMEz75m9tEVqnKg0bG/h1liC07fOb/zMKS3pMsMf4dJl/OjYwouYM49wdP+oJB2Iz+DtldTzmCFIXoXWCg0v7r0+qPyUCHGaWMXnS6HZDyyEmVZX2950L4QxE6mV7sEea1kty2nnIcth9uivKRUg4FvbsG5GnkP+YFOACmcW6gqlcV69p4xBz8XcZcHi3kRg+mayiSf2v0FCFUYpMk3o4ouqJnQ7d78iUp1vwrTAMtKAT9or3LhDd1g730dzzjYTtpUJRrhq1LYA1dj2G/6lQwD3TGtEbVqEA5xFdLocR/DC3spWAi5mF5ERwwX+lwsF7uRDMsLnDsCfuwbBIamKzOaSew78N75VBe/Abv4JjNW3PVRRtNjgRyFsJYDyeOx///eM3B+I3udrSAdGG71wdpJ1VVoo8qn9Na+vGxGYCKeTY8xXT4JNOd9y+00iBkTWhqxBqR/h0HIsJuiAxjCt+SiyUKIJ2YPbfi1bN1UTOCi/j1kY4i1QJYlWc9n2ljyV51xovLC7gG6fiSVzxNPHgGCu3LXlVcL764D9ragDnzpkxzXEHaMmIDMRshuDZz3on6DzRIi1rdNNdIaL6lfl/35RbWFlr8ihPzbL8HtEqytWcfuN6266A88+4J6z60Vids=
  - secure: nlFa/e3p+aF+JFU71GYNxXvq4H7DB0cfq4V01O6Q45P3oqr2dRdVJM8dCBJApmHkkxuGLeAlxPTNf0zB5tQnJ5Ty54nA+c8WpcWUmmEEEeTVZ9l36+xsWf+pd0GMCAE2ibMJ6BhtJKPvkI9Z+NeMy2Eo3wwHsNKbgephXLPNFzdXPBzEWe81P+7c3dTod/+CGTOhqLYMcExEQv6P3jX0DqUHIzDh4YFeaSTPrBpWxdvMlU8lZ5+VczaYFRWwsn+oB2CxrQB3SBl4v8YbUyBZcfoFXd81WM9vxPszKgMXAp1YY74JoJa2678etb5GpVrQ81Vvvyee4ov4fDR2eYMTh5LfFJStoOdf3lrXy9z8ur3/A4z6ycYeW/serag/7lwqt+wVYY+mVrEMh3xS80zYfMC2e1r4YnKH0OJs+mgCTRhhH0w1MH03/McSsjAm1pTPb6RcQIP0wG3aXi9spJayCdbmKxLmALSpCRSbAvN9viId0i4NXQUkYnqbDHbZnHyP/tjP6TWTJUC55+xGiF+XQuqteVsE6Jd5Wgt3JxdeNCKnQ8OGtNwF2jWR5kR8O9lneRY/OCA5wamd4tihNVI1yK5Y3J8it17n9lmYzwFVTMF/c7yklP2/Hx+1zt9hkZS2Ypcar3gOH+4rtCstvxPPdApari9TIEgMiwsVpblO1sQ=
